version: '3.7'

services:
  events:
    container_name: events
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - public
    ports:
      - '5000:5000'
    depends_on:
      - redis
    command: ['python', 'start.py']
  redis:
    container_name: redis
    restart: always
    image: redis:4.0
    networks:
      - public
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  public:
    driver: bridge