# Run (build images / create contianers): docker-compose up -d

version: '3.7'

services:
  events:
    container_name: events
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - public
    ports:
      - '5000:5000'
    depends_on:
      - redis
    volumes:
      - ./source:/code/source/
      - ./log:/code/log/
    command: ['python', './source/start.py']
  redis:
    container_name: redis
    restart: always
    image: redis:4.0
    networks:
      - public
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  public:
    driver: bridge